spring.application.name=PhonePayTransactionApp

# Thymeleaf Configuration
spring.thymeleaf.check-template-location=false

# Logging Configuration
logging.level.in.insta=INFO
logging.level.org.springframework=WARN